// laravel-vue/resources/js/Pages/components/Sponsors.vue
<template>
    <div class="bg-white">
        <div class="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:py-4 lg:px-8">
            <p class="mt-6 text-center text-3xl font-extrabold text-gray-900">We are Proudly Sponsored by</p>
            <div class="mt-6 grid grid-cols-2 gap-0.5 md:grid-cols-3 lg:mt-8">
                <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50">
                    <img class="max-h-20"
                         src="https://raw.githubusercontent.com/MCKevmeister/web701/main/laravel-vue/resources/images/food_truck_food.png"
                         alt="Food Truck Food">
                </div>
                <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50">
                    <img class="max-h-20"
                         src="https://raw.githubusercontent.com/MCKevmeister/web701/main/laravel-vue/resources/images/Nelson_food.png"
                         alt="Nelson Food">
                </div>
                <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50">
                    <img class="max-h-20"
                         src="https://raw.githubusercontent.com/MCKevmeister/web701/main/laravel-vue/resources/images/generic_company_logo.png"
                         alt="ABC generic company">
                </div>
                <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50"/>
                <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50">
                    <img class="max-h-20"
                         src="https://raw.githubusercontent.com/MCKevmeister/web701/main/laravel-vue/resources/images/your%20logo%20here.png"
                         alt="Your Logo Here">
                </div>
                <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50">
                </div>
            </div>
        </div>
    </div>

</template>

<script>
import {defineComponent} from 'vue'

export default defineComponent({
    name: "Sponsors"
})
</script>

// laravel-svelte/resources/js/Pages/Components/Sponsors.svelte
<div class="bg-white">
    <div class="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:py-4 lg:px-8">
            <p class="mt-6 text-center text-3xl font-extrabold text-gray-900">We are Proudly Sponsored by</p>
        <div class="mt-6 grid grid-cols-2 gap-0.5 md:grid-cols-3 lg:mt-8">
            <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50">
                <img class="max-h-20" src="https://raw.githubusercontent.com/MCKevmeister/web701/main/laravel-svelte/resources/images/food_truck_food.png" alt="Food Truck Food">
            </div>
            <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50">
                <img class="max-h-20" src="https://raw.githubusercontent.com/MCKevmeister/web701/main/laravel-svelte/resources/images/Nelson_food.png" alt="Nelson Food">
            </div>
            <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50">
                <img class="max-h-20" src="https://raw.githubusercontent.com/MCKevmeister/web701/main/laravel-svelte/resources/images/generic_company_logo.png" alt="ABC generic company">
            </div>
            <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50">
<!--                <img class="max-h-20" src="https://iacctexas.cividesk.com/files/civicrm/persist/contribute/images/your%20logo%20here.png" alt="Your Logo Here">-->
            </div>
            <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50">
                <img class="max-h-20" src="https://raw.githubusercontent.com/MCKevmeister/web701/main/laravel-svelte/resources/images/your%20logo%20here.png" alt="Your Logo Here">
            </div>
            <div class="col-span-1 flex justify-center py-8 px-8 bg-gray-50">
<!--                <img class="max-h-20" src="https://iacctexas.cividesk.com/files/civicrm/persist/contribute/images/your%20logo%20here.png" alt="Your Logo Here">-->
            </div>
        </div>
    </div>
</div>
