// laravel-svelte/resources/js/Pages/Home.svelte
<script>
    import ContactForm from "./Components/ContactForm.svelte";
    import Sponsors from "./Components/Sponsors.svelte";
    import NavBar from "./Components/NavBar.svelte";
    import Logo from "./Components/Logo.svelte";

    export let auth;

</script>

<NavBar/>
<Logo />
<Sponsors/>
<ContactForm/>

// laravel-vue/resources/js/Pages/Home.vue
<template>
    <NavBar/>
    <Logo />
    <Sponsors />
    <ContactForm/>
</template>

<script setup>
import NavBar from './components/NavBar.vue'
import Logo from './components/Logo.vue'
import Sponsors from './components/Sponsors.vue'
import ContactForm from './components/ContactForm.vue'

</script>
